[project]
name = "dashboard"
# use dynamic version to avoid sync issues with uv.lock after 'release-please'
dynamic = ["version"]
requires-python = ">=3.14"
dependencies = [
    "cleanstack[mongo]",
    "fastapi[standard]==0.141.1",
    "itsdangerous==2.2.0",
    "pwdlib[argon2]==0.3.1",
    "pydantic-settings==2.15.0",
    "pyjwt==2.13.0",
    "pymongo==4.17.0",
    "tactill",
]

[dependency-groups]
dev = [
    "mypy==2.3.1",
    "pytest==9.1.1",
    "ruff==0.16.5",
    "ty==0.0.75",
]

[tool.uv.sources]
cleanstack = { git = "https://github.com/julienpillaud/cleanstack.git", tag = "0.30.0" }
tactill = { git = "https://github.com/julienpillaud/tactill.git", tag = "0.17.0" }

[tool.ruff]
output-format = "concise"

[tool.ruff.lint]
select = [
    "E", "W", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
    "PL", # Pylint
    "RUF",
    "ANN", # flake8-annotations
]
ignore = [
    "PLR0913", # too-many-arguments
    "PLR0917", # Too many positional arguments (7 > 5)
]

[tool.ty.terminal]
output-format = "concise"

[tool.ty.rules]
missing-type-argument = "error"
possibly-unresolved-reference = "warn"
unsound-return-statement = "error"

[tool.mypy]
strict = true
plugins = ['pydantic.mypy']
disable_error_code = [
    "prop-decorator",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "skip_on_ci",
]
log_cli = true
log_cli_level = "info"
log_cli_format = "%(asctime)s [%(levelname)8s] %(name)30s - %(message)s"
